# Generated by Django 3.2.6 on 2022-02-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='traveldb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(null=True, upload_to='image')),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
