# Generated by Django 3.2.6 on 2022-02-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtravelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='traveldb',
            new_name='traveldbs',
        ),
    ]
